---
title: "R Notebook"
---

```{r}
library(tidyverse)
library(future.apply)

source("hussey_hughes.R")

random_seed <- 54287943

# Vb_range <- c(.005, .01, .02, .03, .04, .05)

Vb_range <- .05

reps_per_Vb <- 6400

plan(multisession)

simulation_objects <- future_lapply(
  X = Vb_range,
  FUN = function(Vb) run_hussey_hughes(Va = .005, Vb = Vb, Nreps = reps_per_Vb),
  future.seed = random_seed)

saveRDS(simulation_objects, "vb_simulations_test.rds")
```

```{r}
simulation_params <- simulation_objects |> 
  map_df(~ .x[["parameters"]])

simulation_results <- simulation_objects |> 
  map_df(~ .x[["results"]])

results_df <- bind_cols(simulation_params, simulation_results) |> 
  select(Vb = `Var b`, starts_with("Prob")) |> 
  pivot_longer(
    cols = -Vb,
    names_to = "design",
    names_pattern = "Prob\\.Tval\\.(.*)\\.alt",
    values_to = "power") |> 
  mutate(
    design = case_when(
      design == "par" ~ "Parallel Groups",
      design == "sw" ~ "Stepped Wedge"))

results_df
```

```{r}
p <- ggplot(results_df, aes(x = factor(Vb), y = power, fill = design)) +
  geom_bar(stat = "identity", position = "dodge", color = "grey20") +
  scale_fill_grey(start = .40) +
  labs(
    y = "Power",
    x = "Intraclass Correlation",
    fill = "Design") +
  theme_bw() +
  theme(
    text = element_text(size = 14),
    legend.position = "bottom")

ggsave("stepped_vs_parallel_power.png", plot = p, width = 8, height = 7)

p
```

