---
title: "R Notebook"
---

```{r}
library(tidyverse)

n_timepoints <- 10
n_sites <- 10
subjects_per_site <- 20
n_samples <- 100

condition_mean_diff <- .10

icc <- c(.005, .01, .05, .10, .20)
total_variance <- 1

parallel_design <- matrix(nrow = n_sites, ncol = n_timepoints)
parallel_design[seq(1, round(n_sites/2)), ] <- 0
parallel_design[is.na(parallel_design)] <- 1

stepped_wedge <- matrix(nrow = n_sites, ncol = n_timepoints)
stepped_wedge[lower.tri(stepped_wedge)] <- 0
stepped_wedge[is.na(stepped_wedge)] <- 1
```

```{r}
design_to_dataframe <- function(design_matrix, design){
  design_matrix |> 
    as.data.frame() |> 
    pivot_longer(
      cols = everything(), 
      names_to = "time",
      names_pattern = "V(.)",
      names_transform = as.numeric,
      values_to = "condition") |> 
    mutate(
      design = design,
      site = row_number()) |> 
    select(design, site, time, condition)
}
```

```{r}
design_df <- bind_rows(
  design_to_dataframe(parallel_design, "parallel"),
  design_to_dataframe(stepped_wedge, "rollout"))
```

```{r}
sample_df <- design_df |> 
  expand_grid(
    sample_id = seq(n_samples), 
    icc = icc, 
    subject_id = seq(subjects_per_site)) |>
  group_by(sample_id, icc, design) |> 
  mutate(subject_id = row_number()) |> # make subjects unique in a sample/design
  ungroup() |> 
  select(sample_id, everything()) |> 
  arrange(sample_id, design, site, time, condition, subject_id)
```
```{r}
sample_df <- sample_df |> 
  mutate(
    condition_effect = case_when(
      condition == 0 ~ 0,
      condition == 1 ~ condition_mean_diff))
```

```{r}
sample_df <- sample_df |> 
  group_by(sample_id, icc, site) |> 
  mutate(
    site_variance = icc*total_variance,
    site_intercept = rnorm(n = 1, sd = sqrt(site_variance))) |> 
  ungroup()

sample_df
```

```{r}
sample_df <- sample_df |> 
  group_by(sample_id, icc, subject_id, time) |> 
  mutate(
    residual_variance = (1 - icc)*total_variance,
    random_error = rnorm(n = 1, sd = sqrt(residual_variance))) |> 
  ungroup()
```

```{r}
sample_df <- sample_df |> 
  mutate(outcome = condition_effect + site_intercept + random_error)
```

```{r}
library(future.apply)

plan(multisession)

model_df <- sample_df |> 
  group_by(sample_id, icc, design) |> 
  nest() |>
  ungroup()

model_fits <- future_lapply(
  X = model_df |> 
    pull(data),
  FUN = function(sample_data) 
    lmerTest::lmer(outcome ~ condition + (1 | site), data = sample_data))

model_df <- model_df |> 
  mutate(
    fit = model_fits,
    statistics = map(fit, broom.mixed::tidy))
```

```{r}
results_df <- model_df |> 
  select(sample_id, icc, design, statistics) |> 
  unnest(statistics)
  
power_df <- results_df |> 
  filter(term == "condition") |> 
  mutate(bias = estimate - condition_mean_diff) |> 
  group_by(design, icc) |> 
  summarise(
    n_samples = n(),
    bias = mean(bias),
    power = mean(p.value < .05)) |> 
  arrange(icc, design)

power_df
```

```{r}
ggplot(power_df, aes(x = factor(icc), y = power, fill = design)) +
  geom_bar(stat = "identity", position = "dodge2") +
  scale_fill_grey(start = .40) +
  labs(
    fill = "Design",
    y = "Power",
    x = "ICC") +
  theme_bw()

ggsave("example.png")
```



